tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dummy
      user: dummy
      role: ACCOUNTADMIN
      database: tasty_bytes_dbt_db
      schema: dev
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: dummy
      user: dummy
      role: ACCOUNTADMIN
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh
